### ISSUE TITLE
Possible to suppress keys?

### ISSUE THREAD

**Issue by Lockem90** [michel-pi/LowLevelInput.Net#1]
This isn't so much an issue, and more of a feature request... would it be possible to implement a way to suppress a key from being sent with this method of hooking?

**Comment by michel-pi** [comment]
https://github.com/michel-pi/LowLevelInput.Net/blob/master/LowLevelInput/LowLevelInput/WindowsHooks/WindowsHook.cs#L68
you would need to set nCode to non-zero and wParam and lParam to IntPtr.Zero and call the next hook.

i would need to change the WindowsHook event to allow a bool return value to actually decide if a key will be suppressed or not.

the usage of tasks in https://github.com/michel-pi/LowLevelInput.Net/blob/master/LowLevelInput/LowLevelInput/Hooks/LowLevelKeyboardHook.cs would not allow this decision to be taken by the users code inside the event.

would it still fit your needs if there is a list of VirtualKeyCodes to be suppressed or do you need to take the decision inside the hook?

**Comment by Lockem90** [comment]
Ah ok, I assume it would need to be inside the hook. I'm trying to create a "cursor lock" for a game to simulate fps style aiming (and binding to mouse buttons). Due to mechanics in the game, the mouse breaks it's lock state when pressed, I'm working around the issue by sending it back down whenever this happens, but I was hoping for a cleaner solution... I'm not sure how much work it would be for you to implement this, but I would be willing to donate if its not too bad. I really like your hook implementation :D

**Comment by michel-pi** [comment]
let me think of it a bit.
i am not quite sure how the implementation will look like. maybe give me 2 days

**Comment by Lockem90** [comment]
Ok, sounds good. Thanks!

**Comment by michel-pi** [comment]
hey,
i just added https://github.com/michel-pi/LowLevelInput.Net/blob/master/LowLevelInput/LowLevelInput/WindowsHooks/WindowsHookFilter.cs and https://github.com/michel-pi/LowLevelInput.Net/blob/master/LowLevelInput/LowLevelInput/WindowsHooks/WindowsHook.cs#L72

this will allow you to block input whenever you want.

Example of blocking the A key: https://github.com/michel-pi/LowLevelInput.Net/blob/master/Example/Example/Program.cs#L55

i am going to finish that after those changes mentioned below.

Breaking changes coming soon:
- swap parameters (VirtualKeyCode key, KeyState state) to (KeyState state, VirtualKeyCode key) more logically?
- rename some window messages and virtual key codes so they still fit the naming guidelines

and i am going to change the first LowLevelInput folder name to Project

**Comment by Lockem90** [comment]
Just got a chance to test it, works great so far. Thanks a  lot!

**Comment by michel-pi** [comment]
the new NuGet package is out.

you can create a new issue if you need to handle Mouse inputs in that filter event.

and dont block the filter event's thread. you will delay global windows input otherwise.

and of course i appreciate that donation 👍
