### ISSUE TITLE
Suppress mouse input

### ISSUE THREAD

**Issue by Lockem90** [michel-pi/LowLevelInput.Net#2]
Filtering works great, but I do need to suppress mouse input too. Sorry if it's a lot of work.

**Comment by michel-pi** [comment]
hey,
no problem.

do you only need to know about mouse presses?
or are you also interested in mouse move, scroll and so on?

**Comment by michel-pi** [comment]
maybe BlockInput https://msdn.microsoft.com/en-us/library/windows/desktop/ms646290(v=vs.85).aspx is better for you? or are these still only some keys to block?
and please dont use this to block input in any of YOUR windows. you can achieve that another way :D

**Comment by Lockem90** [comment]
For my project I would only care about about suppressing press / release. I've looked at block input, it will not work for what I'm doing sadly.

**Comment by michel-pi** [comment]
i will probably rewrite https://github.com/michel-pi/LowLevelInput.Net/blob/master/Project/LowLevelInput/Hooks/LowLevelMouseHook.cs#L132 to use a helper method to get it's data.

then i will use the same in the filter method.

(if you are interested, here you can compare the above method to only keyboard messages https://github.com/michel-pi/LowLevelInput.Net/blob/master/Project/LowLevelInput/Hooks/LowLevelKeyboardHook.cs#L104)

i will have time for it tomorrow.

it's not that much work and this library should contain all those features ;)

**Comment by michel-pi** [comment]
i updated the nuget package and added https://github.com/michel-pi/LowLevelInput.Net/blob/master/Project/LowLevelInput/HelperMethods.cs#L12

it now catches mouse input. currently, mouse move and scroll will have KeyState.Pressed and in case of scroll the VirtualKeyCode.Scroll.

it currently does not deliver mouse data like x and y coordinates and scroll position.

**Comment by Lockem90** [comment]
Thanks, for all the work. Exactly what I was looking for!
