### ISSUE TITLE
Option to not initialize mousehook in inputmanager.

### ISSUE THREAD

**Issue by calledude** [michel-pi/LowLevelInput.Net#4]
I have a project where I don't care about mouse-hooking at all. I only listen to a select few keypresses and since InputManager has a nice subscription-system on a per-key-basis I use that. But debugging the program becomes a pain because the mouse-hook is installed no matter what and you can't disable it, the mouse is extremely sluggish as a result.
Are you still working on this project at all?

**Comment by michel-pi** [comment]
Not really. Kinda finished and stopped due to the limitation .Net has.
The c# debugger pauses the whole program and thats why the hooks cause the system to lag.
There is no known way to prevent this.

**Comment by calledude** [comment]
This issue is not visible when using the `LowLevelKeyboardHook` without anything else, because the mousehook isn't installed then, what I'm asking is for a way to use InputManager without having the mousehook getting installed at all. This should be an easy fix, and honestly I might just whip something up myself if you're up for publishing it to nuget later on :)

**Comment by michel-pi** [comment]
if you want to modify the keyboardHook class to add your functionality to it then i would be up to accept a pull request :)

**Comment by calledude** [comment]
#5

**Comment by calledude** [comment]
Hey, just checking in to see if you're going to update the nuget package anytime soon. Thanks
