### ISSUE TITLE
Example - Build Error

### ISSUE THREAD

**Issue by luckyluka** [michel-pi/LowLevelInput.Net#7]
![slika](https://user-images.githubusercontent.com/9536490/128767459-90977fc1-ee00-4b9f-8952-988e9c87edce.png)

![slika](https://user-images.githubusercontent.com/9536490/128767390-83efa343-acdf-4150-b701-9e2442dba3cf.png)

**Comment by michel-pi** [comment]
what are you compiling.

The errors tell you exactly what you need to do

**Comment by luckyluka** [comment]
I was compiling your example.  That is why it seemed strange. Did you try to compile it?

**Comment by michel-pi** [comment]
Just change the method signature
